import { describe, it, expect } from 'vitest';
import { InMemoryGameRepository } from './InMemoryGameRepository.js';
import { Game } from '@chess/domain';

describe('InMemoryGameRepository', () => {
    it('should save and find a game by id', async () => {
        const repo = new InMemoryGameRepository();
        const game = Game.create();

        // In our simplified logic, id might be generated by repo or passed. 
        // Let's assume repo assigns an ID or we map them. For now, since Game doesn't have ID,
        // we'll pass an ID alongside save, or assume the repo generates it and returns it.
        // Actually the Game doesn't have an ID property in domain yet.
        // Let's just test storing and retrieving.
        await repo.save('test-id-1', game);

        const retrieved = await repo.findById('test-id-1');
        expect(retrieved).toBeDefined();
        expect(retrieved?.turn).toBe('w');
    });

    it('should list all games', async () => {
        const repo = new InMemoryGameRepository();
        await repo.save('1', Game.create());
        await repo.save('2', Game.create());

        const games = await repo.findAll();
        expect(games.length).toBe(2);
    });
});
