// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: gaze.proto

package gazev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Gazer_Watch_FullMethodName = "/gaze.v1.Gazer/Watch"
)

// GazerClient is the client API for Gazer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Gazer is the main gRPC service for the Gaze observer.
type GazerClient interface {
	// Watch streams MetricEvents to the caller in real time.
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetricEvent], error)
}

type gazerClient struct {
	cc grpc.ClientConnInterface
}

func NewGazerClient(cc grpc.ClientConnInterface) GazerClient {
	return &gazerClient{cc}
}

func (c *gazerClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetricEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Gazer_ServiceDesc.Streams[0], Gazer_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, MetricEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Gazer_WatchClient = grpc.ServerStreamingClient[MetricEvent]

// GazerServer is the server API for Gazer service.
// All implementations must embed UnimplementedGazerServer
// for forward compatibility.
//
// Gazer is the main gRPC service for the Gaze observer.
type GazerServer interface {
	// Watch streams MetricEvents to the caller in real time.
	Watch(*WatchRequest, grpc.ServerStreamingServer[MetricEvent]) error
	mustEmbedUnimplementedGazerServer()
}

// UnimplementedGazerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGazerServer struct{}

func (UnimplementedGazerServer) Watch(*WatchRequest, grpc.ServerStreamingServer[MetricEvent]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedGazerServer) mustEmbedUnimplementedGazerServer() {}
func (UnimplementedGazerServer) testEmbeddedByValue()               {}

// UnsafeGazerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GazerServer will
// result in compilation errors.
type UnsafeGazerServer interface {
	mustEmbedUnimplementedGazerServer()
}

func RegisterGazerServer(s grpc.ServiceRegistrar, srv GazerServer) {
	// If the following call panics, it indicates UnimplementedGazerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Gazer_ServiceDesc, srv)
}

func _Gazer_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GazerServer).Watch(m, &grpc.GenericServerStream[WatchRequest, MetricEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Gazer_WatchServer = grpc.ServerStreamingServer[MetricEvent]

// Gazer_ServiceDesc is the grpc.ServiceDesc for Gazer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gazer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gaze.v1.Gazer",
	HandlerType: (*GazerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _Gazer_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gaze.proto",
}
