// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: gaze.proto

package gazev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SortBy controls how metrics are ordered in the stream.
type SortBy int32

const (
	SortBy_SORT_BY_PID_UNSPECIFIED SortBy = 0
	SortBy_SORT_BY_CPU             SortBy = 1
	SortBy_SORT_BY_MEM             SortBy = 2
)

// Enum value maps for SortBy.
var (
	SortBy_name = map[int32]string{
		0: "SORT_BY_PID_UNSPECIFIED",
		1: "SORT_BY_CPU",
		2: "SORT_BY_MEM",
	}
	SortBy_value = map[string]int32{
		"SORT_BY_PID_UNSPECIFIED": 0,
		"SORT_BY_CPU":             1,
		"SORT_BY_MEM":             2,
	}
)

func (x SortBy) Enum() *SortBy {
	p := new(SortBy)
	*p = x
	return p
}

func (x SortBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortBy) Descriptor() protoreflect.EnumDescriptor {
	return file_gaze_proto_enumTypes[0].Descriptor()
}

func (SortBy) Type() protoreflect.EnumType {
	return &file_gaze_proto_enumTypes[0]
}

func (x SortBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortBy.Descriptor instead.
func (SortBy) EnumDescriptor() ([]byte, []int) {
	return file_gaze_proto_rawDescGZIP(), []int{0}
}

// WatchRequest parameters for a streaming Watch call.
type WatchRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	SortBy SortBy                 `protobuf:"varint,1,opt,name=sort_by,json=sortBy,proto3,enum=gaze.v1.SortBy" json:"sort_by,omitempty"`
	// top_n limits the number of processes returned per tick (0 = all).
	TopN int32 `protobuf:"varint,2,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"`
	// interval_ms controls the streaming interval (default 2000ms).
	IntervalMs    int32 `protobuf:"varint,3,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_gaze_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gaze_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_gaze_proto_rawDescGZIP(), []int{0}
}

func (x *WatchRequest) GetSortBy() SortBy {
	if x != nil {
		return x.SortBy
	}
	return SortBy_SORT_BY_PID_UNSPECIFIED
}

func (x *WatchRequest) GetTopN() int32 {
	if x != nil {
		return x.TopN
	}
	return 0
}

func (x *WatchRequest) GetIntervalMs() int32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

// MetricEvent carries information about a single process at a point in time.
type MetricEvent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Pid        int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CpuPercent float64                `protobuf:"fixed64,3,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemBytes   uint64                 `protobuf:"varint,4,opt,name=mem_bytes,json=memBytes,proto3" json:"mem_bytes,omitempty"`
	// unix epoch milliseconds
	TimestampMs int64 `protobuf:"varint,5,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// event_kind is non-empty for lifecycle events (started / exited / threshold_breached).
	EventKind     string `protobuf:"bytes,6,opt,name=event_kind,json=eventKind,proto3" json:"event_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricEvent) Reset() {
	*x = MetricEvent{}
	mi := &file_gaze_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricEvent) ProtoMessage() {}

func (x *MetricEvent) ProtoReflect() protoreflect.Message {
	mi := &file_gaze_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricEvent.ProtoReflect.Descriptor instead.
func (*MetricEvent) Descriptor() ([]byte, []int) {
	return file_gaze_proto_rawDescGZIP(), []int{1}
}

func (x *MetricEvent) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *MetricEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricEvent) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *MetricEvent) GetMemBytes() uint64 {
	if x != nil {
		return x.MemBytes
	}
	return 0
}

func (x *MetricEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *MetricEvent) GetEventKind() string {
	if x != nil {
		return x.EventKind
	}
	return ""
}

var File_gaze_proto protoreflect.FileDescriptor

const file_gaze_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"gaze.proto\x12\agaze.v1\"n\n" +
	"\fWatchRequest\x12(\n" +
	"\asort_by\x18\x01 \x01(\x0e2\x0f.gaze.v1.SortByR\x06sortBy\x12\x13\n" +
	"\x05top_n\x18\x02 \x01(\x05R\x04topN\x12\x1f\n" +
	"\vinterval_ms\x18\x03 \x01(\x05R\n" +
	"intervalMs\"\xb3\x01\n" +
	"\vMetricEvent\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vcpu_percent\x18\x03 \x01(\x01R\n" +
	"cpuPercent\x12\x1b\n" +
	"\tmem_bytes\x18\x04 \x01(\x04R\bmemBytes\x12!\n" +
	"\ftimestamp_ms\x18\x05 \x01(\x03R\vtimestampMs\x12\x1d\n" +
	"\n" +
	"event_kind\x18\x06 \x01(\tR\teventKind*G\n" +
	"\x06SortBy\x12\x1b\n" +
	"\x17SORT_BY_PID_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vSORT_BY_CPU\x10\x01\x12\x0f\n" +
	"\vSORT_BY_MEM\x10\x022?\n" +
	"\x05Gazer\x126\n" +
	"\x05Watch\x12\x15.gaze.v1.WatchRequest\x1a\x14.gaze.v1.MetricEvent0\x01B-Z+makinzm/cleanarchitecture/gaze/proto/gazev1b\x06proto3"

var (
	file_gaze_proto_rawDescOnce sync.Once
	file_gaze_proto_rawDescData []byte
)

func file_gaze_proto_rawDescGZIP() []byte {
	file_gaze_proto_rawDescOnce.Do(func() {
		file_gaze_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gaze_proto_rawDesc), len(file_gaze_proto_rawDesc)))
	})
	return file_gaze_proto_rawDescData
}

var file_gaze_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gaze_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gaze_proto_goTypes = []any{
	(SortBy)(0),          // 0: gaze.v1.SortBy
	(*WatchRequest)(nil), // 1: gaze.v1.WatchRequest
	(*MetricEvent)(nil),  // 2: gaze.v1.MetricEvent
}
var file_gaze_proto_depIdxs = []int32{
	0, // 0: gaze.v1.WatchRequest.sort_by:type_name -> gaze.v1.SortBy
	1, // 1: gaze.v1.Gazer.Watch:input_type -> gaze.v1.WatchRequest
	2, // 2: gaze.v1.Gazer.Watch:output_type -> gaze.v1.MetricEvent
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gaze_proto_init() }
func file_gaze_proto_init() {
	if File_gaze_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gaze_proto_rawDesc), len(file_gaze_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gaze_proto_goTypes,
		DependencyIndexes: file_gaze_proto_depIdxs,
		EnumInfos:         file_gaze_proto_enumTypes,
		MessageInfos:      file_gaze_proto_msgTypes,
	}.Build()
	File_gaze_proto = out.File
	file_gaze_proto_goTypes = nil
	file_gaze_proto_depIdxs = nil
}
