#include "test_helper.h"
#include "infrastructure/jwt.h"
#include <stdlib.h>
#include <string.h>

/* JWT header for HS256 is always: {"alg":"HS256","typ":"JWT"}
 * base64url of that is always:    eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
 * This test pins that so jwt.io compatibility is guaranteed. */
static void test_header_is_standard_hs256(void) {
    char *token = jwt_generate("u", "s", 3600);
    ASSERT(token != NULL);
    /* first segment (before the first '.') must equal the known header */
    const char *dot = strchr(token, '.');
    ASSERT(dot != NULL);
    size_t hdr_len = (size_t)(dot - token);
    char hdr[128] = {0};
    memcpy(hdr, token, hdr_len);
    ASSERT_STR_EQ(hdr, "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9");
    free(token);
}

static void test_generate_and_verify_valid_token(void) {
    char *token = jwt_generate("user1", "mysecret", 3600);
    ASSERT(token != NULL);
    ASSERT_INT_EQ(jwt_verify(token, "mysecret"), 1);
    free(token);
}

static void test_verify_fails_with_wrong_secret(void) {
    char *token = jwt_generate("user1", "mysecret", 3600);
    ASSERT(token != NULL);
    ASSERT_INT_EQ(jwt_verify(token, "wrongsecret"), 0);
    free(token);
}

static void test_verify_fails_with_tampered_signature(void) {
    char *token = jwt_generate("user1", "mysecret", 3600);
    ASSERT(token != NULL);

    /* replace last char of the token to tamper the signature */
    size_t len = strlen(token);
    token[len - 1] = (token[len - 1] == 'A') ? 'B' : 'A';

    ASSERT_INT_EQ(jwt_verify(token, "mysecret"), 0);
    free(token);
}

static void test_verify_fails_empty_token(void) {
    ASSERT_INT_EQ(jwt_verify("", "mysecret"), 0);
}

/* Cross-compatibility: token generated by jwt.io with secret "your-256-bit-secret"
 * Payload has no "exp", so expiration check is skipped.
 * If this passes, our jwt_verify is compatible with jwt.io. */
static void test_verify_jwtio_example_token(void) {
    const char *token =
        "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
        ".eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ"
        ".SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c";
    ASSERT_INT_EQ(jwt_verify(token, "your-256-bit-secret"), 1);
}

int main(void) {
    printf("infrastructure/jwt\n");
    RUN(test_header_is_standard_hs256);
    RUN(test_generate_and_verify_valid_token);
    RUN(test_verify_fails_with_wrong_secret);
    RUN(test_verify_fails_with_tampered_signature);
    RUN(test_verify_fails_empty_token);
    RUN(test_verify_jwtio_example_token);
    SUITE_RESULTS();
}
